
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "GeoCon": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "GeoCon.controller.Committee": [],
  "GeoCon.controller.Legislator": [],
  "GeoCon.controller.SplashScreen": [],
  "GeoCon.model.Bill": [],
  "GeoCon.model.Committee": [],
  "GeoCon.model.Legislator": [],
  "GeoCon.model.Vote": [],
  "GeoCon.store.Bills": [],
  "GeoCon.store.Committees": [],
  "GeoCon.store.Districts": [],
  "GeoCon.store.Legislators": [],
  "GeoCon.store.States": [],
  "GeoCon.store.Votes": [],
  "GeoCon.view.Main": [],
  "GeoCon.view.Settings": [],
  "GeoCon.view.Splash": [],
  "GeoCon.view.bill.List": [],
  "GeoCon.view.bill.Show": [],
  "GeoCon.view.committee.List": [],
  "GeoCon.view.legislator.Bio": [],
  "GeoCon.view.legislator.Info": [],
  "GeoCon.view.legislator.List": [],
  "GeoCon.view.legislator.TabPanel": [],
  "GeoCon.view.vote.List": []
});
Ext.ClassManager.addNameAliasMappings({
  "GeoCon.controller.Committee": [],
  "GeoCon.controller.Legislator": [],
  "GeoCon.controller.SplashScreen": [],
  "GeoCon.model.Bill": [],
  "GeoCon.model.Committee": [],
  "GeoCon.model.Legislator": [],
  "GeoCon.model.Vote": [],
  "GeoCon.store.Bills": [],
  "GeoCon.store.Committees": [],
  "GeoCon.store.Districts": [],
  "GeoCon.store.Legislators": [],
  "GeoCon.store.States": [],
  "GeoCon.store.Votes": [],
  "GeoCon.view.Main": [],
  "GeoCon.view.Settings": [],
  "GeoCon.view.Splash": [],
  "GeoCon.view.bill.List": [],
  "GeoCon.view.bill.Show": [],
  "GeoCon.view.committee.List": [],
  "GeoCon.view.legislator.Bio": [],
  "GeoCon.view.legislator.Info": [],
  "GeoCon.view.legislator.List": [],
  "GeoCon.view.legislator.TabPanel": [],
  "GeoCon.view.vote.List": []
});
