
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "AddressBook": "app",
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "AddressBook.controller.Application": [],
  "AddressBook.model.Contact": [],
  "AddressBook.store.Contacts": [],
  "AddressBook.view.Contacts": [],
  "AddressBook.view.Main": [],
  "AddressBook.view.contact.Edit": [],
  "AddressBook.view.contact.Show": []
});
Ext.ClassManager.addNameAliasMappings({
  "AddressBook.controller.Application": [],
  "AddressBook.model.Contact": [],
  "AddressBook.store.Contacts": [],
  "AddressBook.view.Contacts": [
    "widget.contacts"
  ],
  "AddressBook.view.Main": [
    "widget.mainview"
  ],
  "AddressBook.view.contact.Edit": [
    "widget.contact-edit"
  ],
  "AddressBook.view.contact.Show": [
    "widget.contact-show"
  ]
});
