
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.data.proxy.Kiva": "lib/KivaProxy.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "Kiva": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.data.proxy.Kiva": [],
  "Kiva.controller.Loans": [],
  "Kiva.model.Loan": [],
  "Kiva.store.Loans": [],
  "Kiva.view.Detail": [],
  "Kiva.view.LoanFilter": [],
  "Kiva.view.LoansList": [],
  "Kiva.view.LoansListItem": [],
  "Kiva.view.LoansListItemCompletion": [],
  "Kiva.view.Main": [],
  "Kiva.view.detail.Information": [],
  "Kiva.view.detail.Map": [],
  "Kiva.view.detail.Schedule": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.data.proxy.Kiva": [
    "proxy.kiva"
  ],
  "Kiva.controller.Loans": [],
  "Kiva.model.Loan": [],
  "Kiva.store.Loans": [],
  "Kiva.view.Detail": [
    "widget.detail"
  ],
  "Kiva.view.LoanFilter": [
    "widget.loanfilter"
  ],
  "Kiva.view.LoansList": [
    "widget.loanslist"
  ],
  "Kiva.view.LoansListItem": [
    "widget.loanslistitem"
  ],
  "Kiva.view.LoansListItemCompletion": [],
  "Kiva.view.Main": [
    "widget.mainview"
  ],
  "Kiva.view.detail.Information": [
    "widget.detailInformation"
  ],
  "Kiva.view.detail.Map": [
    "widget.detailMap"
  ],
  "Kiva.view.detail.Schedule": [
    "widget.detailSchedule"
  ]
});
