
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Device": "app",
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Device.controller.Application": [],
  "Device.controller.Camera": [],
  "Device.controller.Connection": [],
  "Device.controller.Contacts": [],
  "Device.controller.Notification": [],
  "Device.controller.Orientation": [],
  "Device.controller.Purchases": [],
  "Device.controller.Push": [],
  "Device.controller.Scheme": [],
  "Device.store.Images": [],
  "Device.view.Camera": [],
  "Device.view.Connection": [],
  "Device.view.Contacts": [],
  "Device.view.Geolocation": [],
  "Device.view.Information": [],
  "Device.view.Main": [],
  "Device.view.Notification": [],
  "Device.view.Orientation": [],
  "Device.view.Purchases": [],
  "Device.view.Push": [],
  "Device.view.camera.ImageList": [],
  "Device.view.camera.ImageView": [],
  "Device.view.contacts.Detail": [],
  "Device.view.push.Register": []
});
Ext.ClassManager.addNameAliasMappings({
  "Device.controller.Application": [],
  "Device.controller.Camera": [],
  "Device.controller.Connection": [],
  "Device.controller.Contacts": [],
  "Device.controller.Notification": [],
  "Device.controller.Orientation": [],
  "Device.controller.Purchases": [],
  "Device.controller.Push": [],
  "Device.controller.Scheme": [],
  "Device.store.Images": [],
  "Device.view.Camera": [
    "widget.camera"
  ],
  "Device.view.Connection": [
    "widget.connection"
  ],
  "Device.view.Contacts": [],
  "Device.view.Geolocation": [
    "widget.geolocation"
  ],
  "Device.view.Information": [],
  "Device.view.Main": [
    "widget.main"
  ],
  "Device.view.Notification": [
    "widget.notification"
  ],
  "Device.view.Orientation": [],
  "Device.view.Purchases": [
    "widget.purchases"
  ],
  "Device.view.Push": [
    "widget.pushnotifications"
  ],
  "Device.view.camera.ImageList": [
    "widget.imageList"
  ],
  "Device.view.camera.ImageView": [
    "widget.imageView"
  ],
  "Device.view.contacts.Detail": [],
  "Device.view.push.Register": [
    "widget.registerpanel"
  ]
});
