
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "Oreilly": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "Oreilly.controller.About": [],
  "Oreilly.controller.Sessions": [],
  "Oreilly.controller.Speakers": [],
  "Oreilly.controller.Tweets": [],
  "Oreilly.model.Session": [],
  "Oreilly.model.Speaker": [],
  "Oreilly.store.SessionSpeakers": [],
  "Oreilly.store.Sessions": [],
  "Oreilly.store.SpeakerSessions": [],
  "Oreilly.store.Speakers": [],
  "Oreilly.store.Tweets": [],
  "Oreilly.store.Videos": [],
  "Oreilly.util.Proxy": [],
  "Oreilly.view.Location": [],
  "Oreilly.view.Main": [],
  "Oreilly.view.Tweets": [],
  "Oreilly.view.about.Card": [],
  "Oreilly.view.about.HtmlPage": [],
  "Oreilly.view.about.List": [],
  "Oreilly.view.about.VideoList": [],
  "Oreilly.view.session.Card": [],
  "Oreilly.view.session.Detail": [],
  "Oreilly.view.session.Info": [],
  "Oreilly.view.session.List": [],
  "Oreilly.view.speaker.Card": [],
  "Oreilly.view.speaker.Detail": [],
  "Oreilly.view.speaker.Info": [],
  "Oreilly.view.speaker.List": [],
  "Oreilly.view.tab.Location": []
});
Ext.ClassManager.addNameAliasMappings({
  "Oreilly.controller.About": [],
  "Oreilly.controller.Sessions": [],
  "Oreilly.controller.Speakers": [],
  "Oreilly.controller.Tweets": [],
  "Oreilly.model.Session": [],
  "Oreilly.model.Speaker": [],
  "Oreilly.store.SessionSpeakers": [],
  "Oreilly.store.Sessions": [],
  "Oreilly.store.SpeakerSessions": [],
  "Oreilly.store.Speakers": [],
  "Oreilly.store.Tweets": [],
  "Oreilly.store.Videos": [],
  "Oreilly.util.Proxy": [],
  "Oreilly.view.Location": [
    "widget.location"
  ],
  "Oreilly.view.Main": [
    "widget.main"
  ],
  "Oreilly.view.Tweets": [
    "widget.tweets"
  ],
  "Oreilly.view.about.Card": [
    "widget.aboutContainer"
  ],
  "Oreilly.view.about.HtmlPage": [
    "widget.htmlPage"
  ],
  "Oreilly.view.about.List": [
    "widget.aboutList"
  ],
  "Oreilly.view.about.VideoList": [
    "widget.videoList"
  ],
  "Oreilly.view.session.Card": [
    "widget.sessionContainer"
  ],
  "Oreilly.view.session.Detail": [
    "widget.session"
  ],
  "Oreilly.view.session.Info": [
    "widget.sessionInfo"
  ],
  "Oreilly.view.session.List": [
    "widget.sessions"
  ],
  "Oreilly.view.speaker.Card": [
    "widget.speakerContainer"
  ],
  "Oreilly.view.speaker.Detail": [
    "widget.speaker"
  ],
  "Oreilly.view.speaker.Info": [
    "widget.speakerInfo"
  ],
  "Oreilly.view.speaker.List": [
    "widget.speakers"
  ],
  "Oreilly.view.tab.Location": [
    "widget.location"
  ]
});
