
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "Twitter": "app",
  "Twitter.proxy.Twitter": "app/proxy/Twitter.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Twitter.controller.Search": [],
  "Twitter.controller.phone.Search": [],
  "Twitter.controller.tablet.Search": [],
  "Twitter.model.Search": [],
  "Twitter.model.Tweet": [],
  "Twitter.profile.Phone": [],
  "Twitter.profile.Tablet": [],
  "Twitter.proxy.Twitter": [],
  "Twitter.store.Searches": [],
  "Twitter.view.Main": [],
  "Twitter.view.SearchBar": [],
  "Twitter.view.SearchList": [],
  "Twitter.view.SearchListItem": [],
  "Twitter.view.TweetList": [],
  "Twitter.view.TweetListItem": [],
  "Twitter.view.TweetListItemText": [],
  "Twitter.view.phone.Main": [],
  "Twitter.view.tablet.Main": []
});
Ext.ClassManager.addNameAliasMappings({
  "Twitter.controller.Search": [],
  "Twitter.controller.phone.Search": [],
  "Twitter.controller.tablet.Search": [],
  "Twitter.model.Search": [],
  "Twitter.model.Tweet": [],
  "Twitter.profile.Phone": [],
  "Twitter.profile.Tablet": [],
  "Twitter.proxy.Twitter": [
    "proxy.twitter"
  ],
  "Twitter.store.Searches": [],
  "Twitter.view.Main": [],
  "Twitter.view.SearchBar": [
    "widget.searchbar"
  ],
  "Twitter.view.SearchList": [
    "widget.searchlist"
  ],
  "Twitter.view.SearchListItem": [
    "widget.searchlistitem"
  ],
  "Twitter.view.TweetList": [
    "widget.tweetlist"
  ],
  "Twitter.view.TweetListItem": [
    "widget.tweetlistitem"
  ],
  "Twitter.view.TweetListItemText": [],
  "Twitter.view.phone.Main": [
    "widget.mainview"
  ],
  "Twitter.view.tablet.Main": [
    "widget.mainview"
  ]
});
