
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "States": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "States.controller.Main": [],
  "States.store.BarStore": [],
  "States.store.GeoStore": [],
  "States.store.PieStore": [],
  "States.store.PyramidStore": [],
  "States.store.RaceStore": [],
  "States.view.Gender": [],
  "States.view.Main": [],
  "States.view.Population": [],
  "States.view.Pyramid": [],
  "States.view.Race": [],
  "States.view.USMap": []
});
Ext.ClassManager.addNameAliasMappings({
  "States.controller.Main": [],
  "States.store.BarStore": [
    "store.BarStore"
  ],
  "States.store.GeoStore": [
    "store.GeoStore"
  ],
  "States.store.PieStore": [
    "store.PieStore"
  ],
  "States.store.PyramidStore": [
    "store.PyramidStore"
  ],
  "States.store.RaceStore": [
    "store.RaceStore"
  ],
  "States.view.Gender": [],
  "States.view.Main": [],
  "States.view.Population": [
    "widget.popu"
  ],
  "States.view.Pyramid": [
    "series.pyramid"
  ],
  "States.view.Race": [],
  "States.view.USMap": [
    "widget.usmap"
  ]
});
