
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "TouchStyle": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "TouchStyle.controller.Category": [],
  "TouchStyle.controller.phone.Category": [],
  "TouchStyle.controller.tablet.Category": [],
  "TouchStyle.model.Category": [],
  "TouchStyle.model.Product": [],
  "TouchStyle.profile.Phone": [],
  "TouchStyle.profile.Tablet": [],
  "TouchStyle.store.Categories": [],
  "TouchStyle.view.Categories": [],
  "TouchStyle.view.Main": [],
  "TouchStyle.view.Products": [],
  "TouchStyle.view.ProductsList": [],
  "TouchStyle.view.phone.Main": [],
  "TouchStyle.view.phone.Products": [],
  "TouchStyle.view.phone.ProductsList": [],
  "TouchStyle.view.tablet.Main": [],
  "TouchStyle.view.tablet.Product": []
});
Ext.ClassManager.addNameAliasMappings({
  "TouchStyle.controller.Category": [],
  "TouchStyle.controller.phone.Category": [],
  "TouchStyle.controller.tablet.Category": [],
  "TouchStyle.model.Category": [],
  "TouchStyle.model.Product": [],
  "TouchStyle.profile.Phone": [],
  "TouchStyle.profile.Tablet": [],
  "TouchStyle.store.Categories": [],
  "TouchStyle.view.Categories": [
    "widget.categories"
  ],
  "TouchStyle.view.Main": [
    "widget.main"
  ],
  "TouchStyle.view.Products": [
    "widget.products"
  ],
  "TouchStyle.view.ProductsList": [
    "widget.productslist"
  ],
  "TouchStyle.view.phone.Main": [],
  "TouchStyle.view.phone.Products": [
    "widget.products"
  ],
  "TouchStyle.view.phone.ProductsList": [],
  "TouchStyle.view.tablet.Main": [],
  "TouchStyle.view.tablet.Product": [
    "widget.product"
  ]
});
