
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "EnergyApp": "app",
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "EnergyApp.controller.Main": [],
  "EnergyApp.model.NavigationModel": [],
  "EnergyApp.store.ChartStore": [],
  "EnergyApp.store.NavigationStore": [],
  "EnergyApp.store.YearStore": [],
  "EnergyApp.view.AreaChart": [],
  "EnergyApp.view.ChartView": [],
  "EnergyApp.view.LineChart": [],
  "EnergyApp.view.Main": [],
  "EnergyApp.view.Navigation": [],
  "EnergyApp.view.YearChart": []
});
Ext.ClassManager.addNameAliasMappings({
  "EnergyApp.controller.Main": [],
  "EnergyApp.model.NavigationModel": [],
  "EnergyApp.store.ChartStore": [
    "store.ChartStore"
  ],
  "EnergyApp.store.NavigationStore": [
    "store.NavigationStore"
  ],
  "EnergyApp.store.YearStore": [
    "store.YearStore"
  ],
  "EnergyApp.view.AreaChart": [
    "widget.area"
  ],
  "EnergyApp.view.ChartView": [
    "widget.chartview"
  ],
  "EnergyApp.view.LineChart": [
    "widget.line"
  ],
  "EnergyApp.view.Main": [],
  "EnergyApp.view.Navigation": [
    "widget.navigation"
  ],
  "EnergyApp.view.YearChart": [
    "widget.year"
  ]
});
