
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "StockApp": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "StockApp.controller.Main": [],
  "StockApp.model.Stock": [],
  "StockApp.sprite.RangeMask": [],
  "StockApp.store.Apple": [],
  "StockApp.store.Autodesk": [],
  "StockApp.store.Google": [],
  "StockApp.store.IBM": [],
  "StockApp.store.Microsoft": [],
  "StockApp.store.MovingAverage": [],
  "StockApp.store.Oracle": [],
  "StockApp.view.Main": [],
  "StockApp.view.Preview": []
});
Ext.ClassManager.addNameAliasMappings({
  "StockApp.controller.Main": [],
  "StockApp.model.Stock": [],
  "StockApp.sprite.RangeMask": [
    "sprite.rangemask"
  ],
  "StockApp.store.Apple": [
    "store.Apple"
  ],
  "StockApp.store.Autodesk": [
    "store.Autodesk"
  ],
  "StockApp.store.Google": [
    "store.Google"
  ],
  "StockApp.store.IBM": [
    "store.IBM"
  ],
  "StockApp.store.Microsoft": [
    "store.Microsoft"
  ],
  "StockApp.store.MovingAverage": [
    "store.Apple"
  ],
  "StockApp.store.Oracle": [
    "store.Oracle"
  ],
  "StockApp.view.Main": [],
  "StockApp.view.Preview": [
    "widget.preview"
  ]
});
